# Generated by Django 3.2.19 on 2023-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='posts',
        ),
    ]
