# Generated by Django 3.2.19 on 2023-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_remove_mood_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
