# Generated by Django 3.2.19 on 2023-06-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_alter_mood_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='emoji',
        ),
    ]
